version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
        # do not allow updates of indirect (transient) dependencies
      - dependency-type: "direct"
